(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["cv"],{

/***/ "./src/routes/cv.svelte":
/*!******************************!*\
  !*** ./src/routes/cv.svelte ***!
  \******************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/routes/cv.svelte generated by Svelte v3.31.0 */


const file = "src/routes/cv.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-5081y3-style";
	style.textContent = "section.svelte-5081y3{}h2.svelte-5081y3{font-size:1.15rem;font-weight:500;color:#6f6f6f}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiY3Yuc3ZlbHRlIiwic291cmNlcyI6WyJjdi5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHN0eWxlPlxuICBzZWN0aW9uIHtcbiAgICAvKiB0ZXh0LWFsaWduOiBjZW50ZXI7ICovXG4gIH1cblxuICBoMiB7XG4gICAgZm9udC1zaXplOiAxLjE1cmVtO1xuICAgIGZvbnQtd2VpZ2h0OiA1MDA7XG4gICAgY29sb3I6ICM2ZjZmNmY7XG4gIH1cbjwvc3R5bGU+XG5cbjxzdmVsdGU6aGVhZD5cbiAgPHRpdGxlPkRhbmJlZSBDaG9uIHwgQ1Y8L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cbjxzZWN0aW9uPlxuICA8aDI+UHVibGljYXRpb25zPC9oMj5cbiAgPG9sPlxuICAgIDxsaT5cbiAgICAgIDxzdHJvbmc+Q2hvbiwgRC48L3N0cm9uZz4sICYgU2l0a2luLCBTLiBCLiAodW5kZXIgMm5kIHJvdW5kIG9mIHJldmlzZSAmXG4gICAgICByZXN1Ym1pdCkuIFNlbGYtYXdhcmVuZXNzOiBBIHJldmlldywgY3JpdGljYWwgYXNzZXNzbWVudCwgYW5kIHN5bnRoZXNpcy5cbiAgICAgIDxzdHJvbmc+PGVtPkFjYWRlbXkgb2YgTWFuYWdlbWVudCBBbm5hbHMuPC9lbT48L3N0cm9uZz5cbiAgICA8L2xpPlxuICAgIDxsaT5cbiAgICAgIDxzdHJvbmc+Q2hvbiwgRC48L3N0cm9uZz4sICYgS2Fra2FyLCBILiAodW5kZXIgcmV2aWV3KS4gTm90aGluZyB0byB3b3JyeTpcbiAgICAgIFdoeSBsaWJlcmFscyB1bmRlcmVzdGltYXRlIGRvbWluYW50IGxlYWRlcnMgYW5kIGFjdCBjb21wbGFjZW50bHkuXG4gICAgICA8c3Ryb25nPjxlbT5Qcm9jZWVkaW5ncyBvZiBOYXRpb25hbCBBY2FkZW15IFNjaWVuY2VzPC9lbT48L3N0cm9uZz5cbiAgICA8L2xpPlxuICAgIDxsaT5cbiAgICAgIERpZWJlbHMsIEsuIEouLCBMZWFyeSwgTS4gUi4sICZcbiAgICAgIDxzdHJvbmc+Q2hvbiwgRC48L3N0cm9uZz5cbiAgICAgICgyMDE4KS4gSW5kaXZpZHVhbCBkaWZmZXJlbmNlcyBpbiBzZWxmaXNobmVzcyBhcyBhIG1ham9yIGRpbWVuc2lvbiBvZlxuICAgICAgcGVyc29uYWxpdHk6IEEgcmVpbnRlcnByZXRhdGlvbiBvZiB0aGUgc2l4dGggcGVyc29uYWxpdHkgZmFjdG9yLlxuICAgICAgPHN0cm9uZz48ZW0+UmV2aWV3IG9mIEdlbmVyYWwgUHN5Y2hvbG9neTwvZW0+PC9zdHJvbmc+LCAyMig0KSwgMzY3LTM3Ni4uXG4gICAgPC9saT5cbiAgICA8bGk+XG4gICAgICA8c3Ryb25nPkNob24sIEQ8L3N0cm9uZz4uLCBUaG9tcHNvbiwgSy4gUi4sICYgUmViZXIsIFAuIEouICgyMDE4KS5cbiAgICAgIE1vdGl2YXRpb24gdG8gYXZvaWQgbG9zcyBpbXByb3ZlcyBpbXBsaWNpdCBza2lsbCBwZXJmb3JtYW5jZS5cbiAgICAgIDxzdHJvbmc+PGVtPkpvdXJuYWwgb2YgRXhwZXJpbWVudGFsIFBzeWNob2xvZ3k6IExlYXJuaW5nLCBNZW1vcnksIGFuZFxuICAgICAgICAgIENvZ25pdGlvbjwvZW0+PC9zdHJvbmc+LCA0NCgyKSwgMzI3LTMzMy5cbiAgICA8L2xpPlxuICA8L29sPlxuPC9zZWN0aW9uPlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUNFLE9BQU8sY0FBQyxDQUFDLEFBRVQsQ0FBQyxBQUVELEVBQUUsY0FBQyxDQUFDLEFBQ0YsU0FBUyxDQUFFLE9BQU8sQ0FDbEIsV0FBVyxDQUFFLEdBQUcsQ0FDaEIsS0FBSyxDQUFFLE9BQU8sQUFDaEIsQ0FBQyJ9 */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let t0;
	let section;
	let h2;
	let t1;
	let t2;
	let ol;
	let li0;
	let strong0;
	let t3;
	let t4;
	let strong1;
	let em0;
	let t5;
	let t6;
	let li1;
	let strong2;
	let t7;
	let t8;
	let strong3;
	let em1;
	let t9;
	let t10;
	let li2;
	let t11;
	let strong4;
	let t12;
	let t13;
	let strong5;
	let em2;
	let t14;
	let t15;
	let t16;
	let li3;
	let strong6;
	let t17;
	let t18;
	let strong7;
	let em3;
	let t19;
	let t20;

	const block = {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Publications");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			ol = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("ol");
			li0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			strong0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("strong");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Chon, D.");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(", & Sitkin, S. B. (under 2nd round of revise &\n      resubmit). Self-awareness: A review, critical assessment, and synthesis.\n      ");
			strong1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("strong");
			em0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("em");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Academy of Management Annals.");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			strong2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("strong");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Chon, D.");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(", & Kakkar, H. (under review). Nothing to worry:\n      Why liberals underestimate dominant leaders and act complacently.\n      ");
			strong3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("strong");
			em1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("em");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Proceedings of National Academy Sciences");
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Diebels, K. J., Leary, M. R., &\n      ");
			strong4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("strong");
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Chon, D.");
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n      (2018). Individual differences in selfishness as a major dimension of\n      personality: A reinterpretation of the sixth personality factor.\n      ");
			strong5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("strong");
			em2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("em");
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Review of General Psychology");
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(", 22(4), 367-376..");
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			strong6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("strong");
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Chon, D");
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("., Thompson, K. R., & Reber, P. J. (2018).\n      Motivation to avoid loss improves implicit skill performance.\n      ");
			strong7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("strong");
			em3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("em");
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Journal of Experimental Psychology: Learning, Memory, and\n          Cognition");
			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(", 44(2), 327-333.");
			this.h();
		},
		l: function claim(nodes) {
			const head_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["query_selector_all"])("[data-svelte=\"svelte-271kzv\"]", document.head);
			head_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SECTION", { class: true });
			var section_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section);
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section_nodes, "H2", { class: true });
			var h2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h2_nodes, "Publications");
			h2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(section_nodes);
			ol = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section_nodes, "OL", {});
			var ol_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(ol);
			li0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ol_nodes, "LI", {});
			var li0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li0);
			strong0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li0_nodes, "STRONG", {});
			var strong0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(strong0);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(strong0_nodes, "Chon, D.");
			strong0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li0_nodes, ", & Sitkin, S. B. (under 2nd round of revise &\n      resubmit). Self-awareness: A review, critical assessment, and synthesis.\n      ");
			strong1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li0_nodes, "STRONG", {});
			var strong1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(strong1);
			em0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(strong1_nodes, "EM", {});
			var em0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(em0);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(em0_nodes, "Academy of Management Annals.");
			em0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			strong1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			li0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(ol_nodes);
			li1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ol_nodes, "LI", {});
			var li1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li1);
			strong2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li1_nodes, "STRONG", {});
			var strong2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(strong2);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(strong2_nodes, "Chon, D.");
			strong2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li1_nodes, ", & Kakkar, H. (under review). Nothing to worry:\n      Why liberals underestimate dominant leaders and act complacently.\n      ");
			strong3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li1_nodes, "STRONG", {});
			var strong3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(strong3);
			em1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(strong3_nodes, "EM", {});
			var em1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(em1);
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(em1_nodes, "Proceedings of National Academy Sciences");
			em1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			strong3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			li1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(ol_nodes);
			li2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ol_nodes, "LI", {});
			var li2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li2);
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li2_nodes, "Diebels, K. J., Leary, M. R., &\n      ");
			strong4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li2_nodes, "STRONG", {});
			var strong4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(strong4);
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(strong4_nodes, "Chon, D.");
			strong4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li2_nodes, "\n      (2018). Individual differences in selfishness as a major dimension of\n      personality: A reinterpretation of the sixth personality factor.\n      ");
			strong5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li2_nodes, "STRONG", {});
			var strong5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(strong5);
			em2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(strong5_nodes, "EM", {});
			var em2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(em2);
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(em2_nodes, "Review of General Psychology");
			em2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			strong5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li2_nodes, ", 22(4), 367-376..");
			li2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(ol_nodes);
			li3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ol_nodes, "LI", {});
			var li3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li3);
			strong6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li3_nodes, "STRONG", {});
			var strong6_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(strong6);
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(strong6_nodes, "Chon, D");
			strong6_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li3_nodes, "., Thompson, K. R., & Reber, P. J. (2018).\n      Motivation to avoid loss improves implicit skill performance.\n      ");
			strong7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li3_nodes, "STRONG", {});
			var strong7_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(strong7);
			em3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(strong7_nodes, "EM", {});
			var em3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(em3);
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(em3_nodes, "Journal of Experimental Psychology: Learning, Memory, and\n          Cognition");
			em3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			strong7_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li3_nodes, ", 44(2), 327-333.");
			li3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			ol_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			section_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			document.title = "Danbee Chon | CV";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h2, "class", "svelte-5081y3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h2, file, 16, 2, 217);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(strong0, file, 19, 6, 261);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(em0, file, 21, 14, 426);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(strong1, file, 21, 6, 418);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li0, file, 18, 4, 250);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(strong2, file, 24, 6, 499);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(em1, file, 26, 14, 659);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(strong3, file, 26, 6, 651);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li1, file, 23, 4, 488);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(strong4, file, 30, 6, 781);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(em2, file, 33, 14, 968);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(strong5, file, 33, 6, 960);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li2, file, 28, 4, 732);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(strong6, file, 36, 6, 1058);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(em3, file, 38, 14, 1207);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(strong7, file, 38, 6, 1199);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li3, file, 35, 4, 1047);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(ol, file, 17, 2, 241);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(section, "class", "svelte-5081y3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section, file, 15, 0, 205);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, section, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section, h2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h2, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section, ol);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ol, li0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li0, strong0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(strong0, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li0, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li0, strong1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(strong1, em0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(em0, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ol, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ol, li1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li1, strong2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(strong2, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li1, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li1, strong3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(strong3, em1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(em1, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ol, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ol, li2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li2, t11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li2, strong4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(strong4, t12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li2, t13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li2, strong5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(strong5, em2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(em2, t14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li2, t15);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ol, t16);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ol, li3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li3, strong6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(strong6, t17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li3, t18);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li3, strong7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(strong7, em3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(em3, t19);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li3, t20);
		},
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(section);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props) {
	let { $$slots: slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Cv", slots, []);
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<Cv> was created with unknown prop '${key}'`);
	});

	return [];
}

class Cv extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-5081y3-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Cv",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Cv);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJjMmMzODcwZjg3MGQzYmEzZTAwYi9jdi5jdi5qcyIsInNvdXJjZXNDb250ZW50IjpbXSwic291cmNlUm9vdCI6IiJ9