(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["cv"],{

/***/ "./src/routes/cv.svelte":
/*!******************************!*\
  !*** ./src/routes/cv.svelte ***!
  \******************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/routes/cv.svelte generated by Svelte v3.31.0 */


const file = "src/routes/cv.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-5081y3-style";
	style.textContent = "section.svelte-5081y3{}h2.svelte-5081y3{font-size:1.15rem;font-weight:500;color:#6f6f6f}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiY3Yuc3ZlbHRlIiwic291cmNlcyI6WyJjdi5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHN0eWxlPlxuICBzZWN0aW9uIHtcbiAgICAvKiB0ZXh0LWFsaWduOiBjZW50ZXI7ICovXG4gIH1cblxuICBoMiB7XG4gICAgZm9udC1zaXplOiAxLjE1cmVtO1xuICAgIGZvbnQtd2VpZ2h0OiA1MDA7XG4gICAgY29sb3I6ICM2ZjZmNmY7XG4gIH1cbjwvc3R5bGU+XG5cbjxzdmVsdGU6aGVhZD5cbiAgPHRpdGxlPkRhbmJlZSBDaG9uIHwgQ1Y8L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cbjxzZWN0aW9uPlxuICA8aDI+UHVibGljYXRpb25zPC9oMj5cbiAgPG9sPlxuICAgIDxsaT5cbiAgICAgIDxzdHJvbmc+Q2hvbiwgRC48L3N0cm9uZz4sICYgU2l0a2luLCBTLiBCLiAodW5kZXIgMm5kIHJvdW5kIG9mIHJldmlzZSAmXG4gICAgICByZXN1Ym1pdCkuIFNlbGYtYXdhcmVuZXNzOiBBIHJldmlldywgY3JpdGljYWwgYXNzZXNzbWVudCwgYW5kIHN5bnRoZXNpcy5cbiAgICAgIDxzdHJvbmc+PGVtPkFjYWRlbXkgb2YgTWFuYWdlbWVudCBBbm5hbHMuPC9lbT48L3N0cm9uZz5cbiAgICA8L2xpPlxuICA8L29sPlxuPC9zZWN0aW9uPlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUNFLE9BQU8sY0FBQyxDQUFDLEFBRVQsQ0FBQyxBQUVELEVBQUUsY0FBQyxDQUFDLEFBQ0YsU0FBUyxDQUFFLE9BQU8sQ0FDbEIsV0FBVyxDQUFFLEdBQUcsQ0FDaEIsS0FBSyxDQUFFLE9BQU8sQUFDaEIsQ0FBQyJ9 */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let t0;
	let section;
	let h2;
	let t1;
	let t2;
	let ol;
	let li;
	let strong0;
	let t3;
	let t4;
	let strong1;
	let em;
	let t5;

	const block = {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Publications");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			ol = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("ol");
			li = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			strong0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("strong");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Chon, D.");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(", & Sitkin, S. B. (under 2nd round of revise &\n      resubmit). Self-awareness: A review, critical assessment, and synthesis.\n      ");
			strong1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("strong");
			em = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("em");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Academy of Management Annals.");
			this.h();
		},
		l: function claim(nodes) {
			const head_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["query_selector_all"])("[data-svelte=\"svelte-271kzv\"]", document.head);
			head_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SECTION", { class: true });
			var section_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section);
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section_nodes, "H2", { class: true });
			var h2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h2_nodes, "Publications");
			h2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(section_nodes);
			ol = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section_nodes, "OL", {});
			var ol_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(ol);
			li = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ol_nodes, "LI", {});
			var li_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li);
			strong0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li_nodes, "STRONG", {});
			var strong0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(strong0);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(strong0_nodes, "Chon, D.");
			strong0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li_nodes, ", & Sitkin, S. B. (under 2nd round of revise &\n      resubmit). Self-awareness: A review, critical assessment, and synthesis.\n      ");
			strong1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li_nodes, "STRONG", {});
			var strong1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(strong1);
			em = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(strong1_nodes, "EM", {});
			var em_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(em);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(em_nodes, "Academy of Management Annals.");
			em_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			strong1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			li_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			ol_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			section_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			document.title = "Danbee Chon | CV";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h2, "class", "svelte-5081y3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h2, file, 16, 2, 217);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(strong0, file, 19, 6, 261);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(em, file, 21, 14, 426);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(strong1, file, 21, 6, 418);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li, file, 18, 4, 250);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(ol, file, 17, 2, 241);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(section, "class", "svelte-5081y3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section, file, 15, 0, 205);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, section, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section, h2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h2, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section, ol);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ol, li);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li, strong0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(strong0, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li, strong1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(strong1, em);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(em, t5);
		},
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(section);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props) {
	let { $$slots: slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Cv", slots, []);
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<Cv> was created with unknown prop '${key}'`);
	});

	return [];
}

class Cv extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-5081y3-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Cv",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Cv);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiI3NmRlMmE1NTRiMTI5M2UyMmZjZC9jdi5jdi5qcyIsInNvdXJjZXNDb250ZW50IjpbXSwic291cmNlUm9vdCI6IiJ9